---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (AlmaLinux)
      tags: always
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "AlmaLinux"

    - name: install updates (Debian)
      tags: always
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Debian"


- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
        mode: 0755
        owner: root
        group: root


- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php for AlmaLinux servers
      tags: apache,httpd,almalinux
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "AlmaLinux"

    - name: install apache and php for Debian servers
      tags: apache,apache2,debian
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Debian"

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644


- hosts: db_servers
  become: true
  tasks: 

    - name: install mariadb package (AlmaLinux)
      tags: db,mariadb,almalinux
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "AlmaLinux"

    - name: install mariadb package (Debian)
      tags: db,mariadb,debian
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Debian"


- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
