---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (AlmaLinux)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "AlmaLinux"

    - name: install updates (Debian)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Debian"


- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php for Debian servers
      tags: apache,apache2,debian
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Debian"

    - name: install apache and php for AlmaLinux servers
      tags: apache,httpd,almalinux
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "AlmaLinux"


- hosts: db_servers
  become: true
  tasks: 

    - name: install mariadb package (Debian)
      tags: db,mariadb,debian
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Debian"

    - name: install mariadb package (AlmaLinux)
      tags: db,mariadb,almalinux
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "AlmaLinux"


- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
