---

- hosts: all
  become: true
  pre_tasks:

    - name: update repository index (AlmaLinux)
      tags: always
      dnf:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "AlmaLinux"

    - name: update repository index (Debian)
      tags: always
      apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Debian"


- hosts: all
  become: true
  tasks:

    - name: add ssh key for simone
      tags: always
      authorized_key:
        user: simone
        key: ""


- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
        mode: 0755
        owner: root
        group: root


- hosts: web_servers
  become: true
  tasks:

    - name: install apache and php for AlmaLinux servers
      tags: apache,httpd,almalinux
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "AlmaLinux"

    - name: start httpd (AlmaLinux)
      tags: apache,httpd,almalinux
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "AlmaLinux"

    - name: open port 80 (AlmaLinux)
      tags: apache,httpd,almalinux
      ansible.posix.firewalld:
        port: 80/tcp
        state: enabled
      when: ansible_distribution == "AlmaLinux"

    - name: install apache and php for Debian servers
      tags: apache,apache2,debian
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Debian"

    - name: change e-mail address for admin
      tags: apache,httpd,almalinux
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somewhere.net
      when: ansible_distribution == "AlmaLinux"
      register: httpd

    - name: restart httpd (AlmaLinux)
      tags: apache,httpd,almalinux
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644


- hosts: db_servers
  become: true
  tasks: 

    - name: install mariadb package (AlmaLinux)
      tags: db,mariadb,almalinux
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "AlmaLinux"

    - name: install mariadb package (Debian)
      tags: db,mariadb,debian
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Debian"


- hosts: file_servers
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
