---

- hosts: all
  become: true
  pre_tasks:

    - name: update repository index (AlmaLinux)
      tags: always
      dnf:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "AlmaLinux"

    - name: update repository index (Debian)
      tags: always
      apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Debian"


- hosts: all
  become: true
  tasks:
  roles:
    - base

- hosts: workstations
  become: true
  tasks:
  roles:
    - workstations

- hosts: web_servers
  become: true
  tasks:
  roles:
    - web_servers

- hosts: db_servers
  become: true
  tasks: 
  roles:
    - db_servers

- hosts: file_servers
  become: true
  tasks:
  roles:
    - file_servers
