- name: install apache and php for AlmaLinux servers
  tags: apache,httpd,almalinux
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "AlmaLinux"

- name: start httpd (AlmaLinux)
  tags: apache,httpd,almalinux
  service:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution == "AlmaLinux"

- name: open port 80 (AlmaLinux)
  tags: apache,httpd,almalinux
  ansible.posix.firewalld:
    port: 80/tcp
    state: enabled
  when: ansible_distribution == "AlmaLinux"

- name: install apache and php for Debian servers
  tags: apache,apache2,debian
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Debian"

- name: change e-mail address for admin
  tags: apache,httpd,almalinux
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "AlmaLinux"
  register: httpd

- name: restart httpd (AlmaLinux)
  tags: apache,httpd,almalinux
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

