- name: install mariadb package
  tags: db,mariadb
  package:
    name: "{{ mariadb_package_name }}"
    state: latest

- name: start and enable mariadb service
  tags: db,mariadb
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true

