- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
    owner: root
    group: root

- name: create system user semaphore
  tags: semaphore
  user:
    system: true
    name: semaphore
    home: /home/semaphore

- name: install mariadb package
  tags: semaphore
  package:
    name: "{{ mariadb_package_name }}"
    state: latest

- name: start and enable mariadb service
  tags: semaphore
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true

- name: install semaphore (AlmaLinux)
  tags: semaphore
  dnf:
    name: https://github.com/semaphoreui/semaphore/releases/download/v2.10.22/semaphore_2.10.22_linux_amd64.rpm
  when: ansible_distribution == "AlmaLinux"

- name: install semaphore (Debian)
  tags: semaphore
  apt:
    deb: https://github.com/semaphoreui/semaphore/releases/download/v2.10.22/semaphore_2.10.22_linux_amd64.deb
  when: ansible_distribution == "Debian"

